/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author yoshi
 */
public class ModuloEncabe extends javax.swing.JPanel {

    /**
     * Creates new form ModuloEncabe
     */
    public ModuloEncabe() {
        initComponents();
        SelecProd.setVisible(false);
        SelecMaq.setVisible(false);
        SelecRepor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabe = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ContenedorProd = new javax.swing.JPanel();
        btnProductos = new javax.swing.JPanel();
        lblAgregar6 = new javax.swing.JLabel();
        SelecProd = new javax.swing.JPanel();
        ContenedorMaq = new javax.swing.JPanel();
        btnMaquina = new javax.swing.JPanel();
        lblAgregar7 = new javax.swing.JLabel();
        SelecMaq = new javax.swing.JPanel();
        ContenedorRepor = new javax.swing.JPanel();
        btnReportes = new javax.swing.JPanel();
        lblAgregar8 = new javax.swing.JLabel();
        SelecRepor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1300, 120));
        setMinimumSize(new java.awt.Dimension(1300, 120));
        setPreferredSize(new java.awt.Dimension(1300, 120));

        Encabe.setBackground(new java.awt.Color(51, 71, 86));
        Encabe.setMaximumSize(new java.awt.Dimension(1300, 120));
        Encabe.setMinimumSize(new java.awt.Dimension(1300, 120));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Logo.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(152, 102));
        jLabel5.setMinimumSize(new java.awt.Dimension(152, 102));
        jLabel5.setName(""); // NOI18N

        ContenedorProd.setBackground(new java.awt.Color(44, 62, 75));
        ContenedorProd.setMaximumSize(new java.awt.Dimension(250, 120));
        ContenedorProd.setMinimumSize(new java.awt.Dimension(250, 120));

        btnProductos.setBackground(new java.awt.Color(5, 102, 116));
        btnProductos.setMaximumSize(new java.awt.Dimension(180, 70));
        btnProductos.setMinimumSize(new java.awt.Dimension(180, 70));
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });

        lblAgregar6.setFont(new java.awt.Font("SF UI Display", 1, 20)); // NOI18N
        lblAgregar6.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar6.setText("Productos");
        lblAgregar6.setMaximumSize(new java.awt.Dimension(160, 38));
        lblAgregar6.setMinimumSize(new java.awt.Dimension(160, 38));
        lblAgregar6.setPreferredSize(new java.awt.Dimension(160, 38));

        SelecProd.setBackground(new java.awt.Color(255, 75, 92));
        SelecProd.setMaximumSize(new java.awt.Dimension(180, 5));
        SelecProd.setMinimumSize(new java.awt.Dimension(180, 5));
        SelecProd.setName(""); // NOI18N

        javax.swing.GroupLayout SelecProdLayout = new javax.swing.GroupLayout(SelecProd);
        SelecProd.setLayout(SelecProdLayout);
        SelecProdLayout.setHorizontalGroup(
            SelecProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SelecProdLayout.setVerticalGroup(
            SelecProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnProductosLayout = new javax.swing.GroupLayout(btnProductos);
        btnProductos.setLayout(btnProductosLayout);
        btnProductosLayout.setHorizontalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SelecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProductosLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(lblAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        btnProductosLayout.setVerticalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosLayout.createSequentialGroup()
                .addComponent(SelecProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProductosLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(lblAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ContenedorProdLayout = new javax.swing.GroupLayout(ContenedorProd);
        ContenedorProd.setLayout(ContenedorProdLayout);
        ContenedorProdLayout.setHorizontalGroup(
            ContenedorProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProdLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        ContenedorProdLayout.setVerticalGroup(
            ContenedorProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorProdLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ContenedorMaq.setBackground(new java.awt.Color(44, 62, 75));
        ContenedorMaq.setMaximumSize(new java.awt.Dimension(250, 120));
        ContenedorMaq.setMinimumSize(new java.awt.Dimension(250, 120));
        ContenedorMaq.setPreferredSize(new java.awt.Dimension(250, 120));

        btnMaquina.setBackground(new java.awt.Color(5, 102, 116));
        btnMaquina.setMaximumSize(new java.awt.Dimension(180, 70));
        btnMaquina.setMinimumSize(new java.awt.Dimension(180, 70));
        btnMaquina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaquinaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaquinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaquinaMouseExited(evt);
            }
        });

        lblAgregar7.setFont(new java.awt.Font("SF UI Display", 1, 20)); // NOI18N
        lblAgregar7.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar7.setText("Maquina");

        SelecMaq.setBackground(new java.awt.Color(255, 75, 92));
        SelecMaq.setMaximumSize(new java.awt.Dimension(180, 5));
        SelecMaq.setMinimumSize(new java.awt.Dimension(180, 5));
        SelecMaq.setName(""); // NOI18N

        javax.swing.GroupLayout SelecMaqLayout = new javax.swing.GroupLayout(SelecMaq);
        SelecMaq.setLayout(SelecMaqLayout);
        SelecMaqLayout.setHorizontalGroup(
            SelecMaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SelecMaqLayout.setVerticalGroup(
            SelecMaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnMaquinaLayout = new javax.swing.GroupLayout(btnMaquina);
        btnMaquina.setLayout(btnMaquinaLayout);
        btnMaquinaLayout.setHorizontalGroup(
            btnMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelecMaq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMaquinaLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(lblAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        btnMaquinaLayout.setVerticalGroup(
            btnMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMaquinaLayout.createSequentialGroup()
                .addComponent(SelecMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(btnMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMaquinaLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(lblAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ContenedorMaqLayout = new javax.swing.GroupLayout(ContenedorMaq);
        ContenedorMaq.setLayout(ContenedorMaqLayout);
        ContenedorMaqLayout.setHorizontalGroup(
            ContenedorMaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorMaqLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        ContenedorMaqLayout.setVerticalGroup(
            ContenedorMaqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorMaqLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContenedorRepor.setBackground(new java.awt.Color(44, 62, 75));
        ContenedorRepor.setMaximumSize(new java.awt.Dimension(250, 120));
        ContenedorRepor.setMinimumSize(new java.awt.Dimension(250, 120));

        btnReportes.setBackground(new java.awt.Color(5, 102, 116));
        btnReportes.setMaximumSize(new java.awt.Dimension(180, 70));
        btnReportes.setMinimumSize(new java.awt.Dimension(180, 70));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });

        lblAgregar8.setFont(new java.awt.Font("SF UI Display", 1, 20)); // NOI18N
        lblAgregar8.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar8.setText("Reportes");

        SelecRepor.setBackground(new java.awt.Color(255, 75, 92));
        SelecRepor.setMaximumSize(new java.awt.Dimension(180, 5));
        SelecRepor.setMinimumSize(new java.awt.Dimension(180, 5));
        SelecRepor.setName(""); // NOI18N

        javax.swing.GroupLayout SelecReporLayout = new javax.swing.GroupLayout(SelecRepor);
        SelecRepor.setLayout(SelecReporLayout);
        SelecReporLayout.setHorizontalGroup(
            SelecReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SelecReporLayout.setVerticalGroup(
            SelecReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnReportesLayout = new javax.swing.GroupLayout(btnReportes);
        btnReportes.setLayout(btnReportesLayout);
        btnReportesLayout.setHorizontalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelecRepor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnReportesLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(lblAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        btnReportesLayout.setVerticalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReportesLayout.createSequentialGroup()
                .addComponent(SelecRepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnReportesLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(lblAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ContenedorReporLayout = new javax.swing.GroupLayout(ContenedorRepor);
        ContenedorRepor.setLayout(ContenedorReporLayout);
        ContenedorReporLayout.setHorizontalGroup(
            ContenedorReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorReporLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        ContenedorReporLayout.setVerticalGroup(
            ContenedorReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorReporLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EncabeLayout = new javax.swing.GroupLayout(Encabe);
        Encabe.setLayout(EncabeLayout);
        EncabeLayout.setHorizontalGroup(
            EncabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabeLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(ContenedorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ContenedorMaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ContenedorRepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        EncabeLayout.setVerticalGroup(
            EncabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorMaq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorRepor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Encabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Encabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
//        ModuloEncabe mEncabe = new ModuloEncabe();
//
//        mEncabe.setSize(new Dimension(1300, 200));
//        mEncabe.setLocation(0,0);
//        ModuloOpeDash.Encabe.removeAll();
//        ModuloOpeDash.Encabe.add(mEncabe,BorderLayout.CENTER);
//        ModuloOpeDash.Encabe.revalidate();
//        ModuloOpeDash.Encabe.repaint();
        
        ModuloProductos mProd = new ModuloProductos();

        mProd.setSize(new Dimension(1300, 680));
        mProd.setLocation(0,0);
        ModuloOpeDash.Principal.removeAll();
        ModuloOpeDash.Principal.add(mProd,BorderLayout.CENTER);
        ModuloOpeDash.Principal.revalidate();
        ModuloOpeDash.Principal.repaint();
        
        SelecProd.setVisible(true);
        SelecMaq.setVisible(false);
        SelecRepor.setVisible(false);
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        btnProductos.setBackground(new Color(45, 130, 130));
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        btnProductos.setBackground(new Color(5,102,116));
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnMaquinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaquinaMouseClicked
        ModuloMaquina mMaq = new ModuloMaquina();

        mMaq.setSize(new Dimension(1300, 680));
        mMaq.setLocation(0,0);
        ModuloOpeDash.Principal.removeAll();
        ModuloOpeDash.Principal.add(mMaq,BorderLayout.CENTER);
        ModuloOpeDash.Principal.revalidate();
        ModuloOpeDash.Principal.repaint();
        
        SelecProd.setVisible(false);
        SelecMaq.setVisible(true);
        SelecRepor.setVisible(false);
    }//GEN-LAST:event_btnMaquinaMouseClicked

    private void btnMaquinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaquinaMouseEntered
        btnMaquina.setBackground(new Color(45, 130, 130));
    }//GEN-LAST:event_btnMaquinaMouseEntered

    private void btnMaquinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaquinaMouseExited
        btnMaquina.setBackground(new Color(5,102,116));
    }//GEN-LAST:event_btnMaquinaMouseExited

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked

        ModuloEncabeRep mOpRe = new ModuloEncabeRep();

        mOpRe.setSize(new Dimension(1300, 200));
        mOpRe.setLocation(0,0);
        ModuloOpeDash.Encabe.removeAll();
        ModuloOpeDash.Encabe.add(mOpRe,BorderLayout.CENTER);
        ModuloOpeDash.Encabe.revalidate();
        ModuloOpeDash.Encabe.repaint();

        ModuloInicioReportes mIniRep = new ModuloInicioReportes();

        mIniRep.setSize(new Dimension(1300, 680));
        mIniRep.setLocation(0,0);
        ModuloOpeDash.Principal.removeAll();
        ModuloOpeDash.Principal.add(mIniRep, BorderLayout.CENTER);
        ModuloOpeDash.Principal.revalidate();
        ModuloOpeDash.Principal.repaint();
    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        btnReportes.setBackground(new Color(45, 130, 130));
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        btnReportes.setBackground(new Color(5,102,116));
    }//GEN-LAST:event_btnReportesMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorMaq;
    private javax.swing.JPanel ContenedorProd;
    private javax.swing.JPanel ContenedorRepor;
    private javax.swing.JPanel Encabe;
    private javax.swing.JPanel SelecMaq;
    private javax.swing.JPanel SelecProd;
    private javax.swing.JPanel SelecRepor;
    private javax.swing.JPanel btnMaquina;
    private javax.swing.JPanel btnProductos;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAgregar6;
    private javax.swing.JLabel lblAgregar7;
    private javax.swing.JLabel lblAgregar8;
    // End of variables declaration//GEN-END:variables
}
