/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author yoshi
 */
public class ModuloEncabeRep extends javax.swing.JPanel {

    /**
     * Creates new form ModulosOp
     */
    public ModuloEncabeRep() {
        initComponents();
        SelecProdTotal.setVisible(false);
        SelecProdDia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabe = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        ContenedorProdDia = new javax.swing.JPanel();
        btnProdDia = new javax.swing.JPanel();
        lblAgregar6 = new javax.swing.JLabel();
        SelecProdDia = new javax.swing.JPanel();
        ContenedorProdTotal = new javax.swing.JPanel();
        btnProdTotal = new javax.swing.JPanel();
        lblAgregar7 = new javax.swing.JLabel();
        SelecProdTotal = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1300, 120));
        setMinimumSize(new java.awt.Dimension(1300, 120));
        setPreferredSize(new java.awt.Dimension(1300, 120));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabe.setBackground(new java.awt.Color(51, 71, 86));
        Encabe.setMaximumSize(new java.awt.Dimension(1300, 120));
        Encabe.setMinimumSize(new java.awt.Dimension(1300, 120));
        Encabe.setPreferredSize(new java.awt.Dimension(1300, 120));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Logo.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(152, 102));
        Logo.setMinimumSize(new java.awt.Dimension(152, 102));
        Logo.setPreferredSize(new java.awt.Dimension(152, 102));

        ContenedorProdDia.setBackground(new java.awt.Color(44, 62, 75));
        ContenedorProdDia.setMaximumSize(new java.awt.Dimension(250, 120));
        ContenedorProdDia.setMinimumSize(new java.awt.Dimension(250, 120));

        btnProdDia.setBackground(new java.awt.Color(5, 102, 116));
        btnProdDia.setMaximumSize(new java.awt.Dimension(180, 70));
        btnProdDia.setMinimumSize(new java.awt.Dimension(180, 70));
        btnProdDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdDiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdDiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdDiaMouseExited(evt);
            }
        });

        lblAgregar6.setFont(new java.awt.Font("SF UI Display", 1, 20)); // NOI18N
        lblAgregar6.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar6.setText("Producto / día");

        SelecProdDia.setBackground(new java.awt.Color(255, 75, 92));
        SelecProdDia.setMaximumSize(new java.awt.Dimension(180, 5));
        SelecProdDia.setMinimumSize(new java.awt.Dimension(180, 5));
        SelecProdDia.setName(""); // NOI18N

        javax.swing.GroupLayout SelecProdDiaLayout = new javax.swing.GroupLayout(SelecProdDia);
        SelecProdDia.setLayout(SelecProdDiaLayout);
        SelecProdDiaLayout.setHorizontalGroup(
            SelecProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SelecProdDiaLayout.setVerticalGroup(
            SelecProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnProdDiaLayout = new javax.swing.GroupLayout(btnProdDia);
        btnProdDia.setLayout(btnProdDiaLayout);
        btnProdDiaLayout.setHorizontalGroup(
            btnProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProdDiaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SelecProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProdDiaLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(lblAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        btnProdDiaLayout.setVerticalGroup(
            btnProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProdDiaLayout.createSequentialGroup()
                .addComponent(SelecProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(btnProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProdDiaLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(lblAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ContenedorProdDiaLayout = new javax.swing.GroupLayout(ContenedorProdDia);
        ContenedorProdDia.setLayout(ContenedorProdDiaLayout);
        ContenedorProdDiaLayout.setHorizontalGroup(
            ContenedorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProdDiaLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        ContenedorProdDiaLayout.setVerticalGroup(
            ContenedorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorProdDiaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ContenedorProdTotal.setBackground(new java.awt.Color(44, 62, 75));
        ContenedorProdTotal.setMaximumSize(new java.awt.Dimension(250, 120));
        ContenedorProdTotal.setMinimumSize(new java.awt.Dimension(250, 120));

        btnProdTotal.setBackground(new java.awt.Color(5, 102, 116));
        btnProdTotal.setMaximumSize(new java.awt.Dimension(180, 70));
        btnProdTotal.setMinimumSize(new java.awt.Dimension(180, 70));
        btnProdTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdTotalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdTotalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdTotalMouseExited(evt);
            }
        });

        lblAgregar7.setFont(new java.awt.Font("SF UI Display", 1, 20)); // NOI18N
        lblAgregar7.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar7.setText("Producto / Total");

        SelecProdTotal.setBackground(new java.awt.Color(255, 75, 92));
        SelecProdTotal.setMaximumSize(new java.awt.Dimension(180, 5));
        SelecProdTotal.setMinimumSize(new java.awt.Dimension(180, 5));
        SelecProdTotal.setName(""); // NOI18N

        javax.swing.GroupLayout SelecProdTotalLayout = new javax.swing.GroupLayout(SelecProdTotal);
        SelecProdTotal.setLayout(SelecProdTotalLayout);
        SelecProdTotalLayout.setHorizontalGroup(
            SelecProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        SelecProdTotalLayout.setVerticalGroup(
            SelecProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnProdTotalLayout = new javax.swing.GroupLayout(btnProdTotal);
        btnProdTotal.setLayout(btnProdTotalLayout);
        btnProdTotalLayout.setHorizontalGroup(
            btnProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProdTotalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SelecProdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProdTotalLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(lblAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        btnProdTotalLayout.setVerticalGroup(
            btnProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProdTotalLayout.createSequentialGroup()
                .addComponent(SelecProdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(btnProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnProdTotalLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(lblAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ContenedorProdTotalLayout = new javax.swing.GroupLayout(ContenedorProdTotal);
        ContenedorProdTotal.setLayout(ContenedorProdTotalLayout);
        ContenedorProdTotalLayout.setHorizontalGroup(
            ContenedorProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProdTotalLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnProdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        ContenedorProdTotalLayout.setVerticalGroup(
            ContenedorProdTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorProdTotalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnProdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EncabeLayout = new javax.swing.GroupLayout(Encabe);
        Encabe.setLayout(EncabeLayout);
        EncabeLayout.setHorizontalGroup(
            EncabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabeLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(ContenedorProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ContenedorProdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        EncabeLayout.setVerticalGroup(
            EncabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorProdDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenedorProdTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(Encabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdDiaMouseClicked
        ModuloReporteProdDia mRep = new ModuloReporteProdDia();

        mRep.setSize(new Dimension(1300, 680));
        mRep.setLocation(0,0);
        ModuloOpeDash.Principal.removeAll();
        ModuloOpeDash.Principal.add(mRep,BorderLayout.CENTER);
        ModuloOpeDash.Principal.revalidate();
        ModuloOpeDash.Principal.repaint();
        
        SelecProdDia.setVisible(true);
        SelecProdTotal.setVisible(false);
    }//GEN-LAST:event_btnProdDiaMouseClicked

    private void btnProdDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdDiaMouseEntered
        btnProdDia.setBackground(new Color(45, 130, 130));
    }//GEN-LAST:event_btnProdDiaMouseEntered

    private void btnProdDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdDiaMouseExited
        btnProdDia.setBackground(new Color(5,102,116));
    }//GEN-LAST:event_btnProdDiaMouseExited

    private void btnProdTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdTotalMouseClicked
        ModuloReporteProdTotal mRep = new ModuloReporteProdTotal();

        mRep.setSize(new Dimension(1300, 680));
        mRep.setLocation(0,0);
        ModuloOpeDash.Principal.removeAll();
        ModuloOpeDash.Principal.add(mRep,BorderLayout.CENTER);
        ModuloOpeDash.Principal.revalidate();
        ModuloOpeDash.Principal.repaint();
        
        SelecProdDia.setVisible(false);
        SelecProdTotal.setVisible(true);
    }//GEN-LAST:event_btnProdTotalMouseClicked

    private void btnProdTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdTotalMouseEntered
        btnProdTotal.setBackground(new Color(45, 130, 130));
    }//GEN-LAST:event_btnProdTotalMouseEntered

    private void btnProdTotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdTotalMouseExited
        btnProdTotal.setBackground(new Color(5,102,116));
    }//GEN-LAST:event_btnProdTotalMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorProdDia;
    private javax.swing.JPanel ContenedorProdTotal;
    private javax.swing.JPanel Encabe;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel SelecProdDia;
    private javax.swing.JPanel SelecProdTotal;
    private javax.swing.JPanel btnProdDia;
    private javax.swing.JPanel btnProdTotal;
    private javax.swing.JLabel lblAgregar6;
    private javax.swing.JLabel lblAgregar7;
    // End of variables declaration//GEN-END:variables
}
